const speakers = [
  // {
  //   id: 1,
  //   photo: "/speakers/2024/karolAttekita.png",
  //   name: "Karol Attekita",
  //   tech: "Mobile",
  //   topic:
  //     "Explorando uma nova abordagem para desenvolvimento mobile com Kotlin Multiplataforma. Vamos explorar os pros e contras dessa tecnologia e enteder quais são as perspectivas para o futuro e como isso pode impactar o mercado mobile",
  //   mini_bio:
  //     "Engenheira de software especialista em aplicativos e games, com mais de 13 anos de experiência e 5 prêmios de reconhecimento nacional. Foi eleita LinkedIn Top Voice 2023 pelo seu trabalho de criação de conteúdo para a comunidade de tecnologia. Em 2022 esteve na lista dos 50 hackers to follow e foi indicada para o prêmio internacional 'Women that build'. Atuou por quase 10 anos como freelancer para equipes multinacionais e possui mais de 20 aplicativos e jogos publicados na App Store. Atualmente é Engenheira iOS na Riot Games (pela X-team) e compartilha conteúdo no canal Attekita Dev onde impacta em suas redes sociais mais de 270 mil pessoas. Acredita que podemos mudar o mundo com o poder da informação!",
  //   title: "Desenvolvimento Mobile com Kotlin Multiplataforma",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "Riot Games",
  //   social_media: {
  //     instagram: "https://www.instagram.com/attekitadev/",
  //     twitter: "",
  //     linkedIn: "http://linkedin.com/in/bullas-attekita/",
  //     github: "https://github.com/Bullas",
  //     website: "http://www.attekita.com",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 2,
  //   photo: "/speakers/2024/erickWendelGDE.png",
  //   name: "Erick Wendel",
  //   tech: "WebXR",
  //   topic:
  //     "Mergulhe no emocionante mundo do WebXR na minha palestra sobre trazer Realidade Virtual (VR) e Realidade Aumentada (AR) diretamente para os navegadores da web. Como desenvolvedor, eu vi como a tecnologia pode despertar a criatividade. Nesta sessão, vou apresentar o framework A-Frame, mostrando como é fácil criar experiências incríveis e interativas na web. Isso não é apenas um tutorial; é um convite para você sair do comum e explorar as infinitas possibilidades de criar aplicativos web envolventes.",
  //   mini_bio:
  //     "Erick Wendel é um palestrante experiente em conferências de tecnologia, conhecido como keynote speaker, e um renomado desenvolvedor da equipe principal do Node.js. Ele já ministrou mais de 100 palestras técnicas em mais de 10 países diferentes em todo o mundo. Erick foi reconhecido como Especialista em Node.js com prêmios de Google Developer Expert, Microsoft MVP, GitHub Stars e OpenJS Path Finder Educator. Além disso, ele é um educador profissional e fundador da empresa https://erickwendel.com, onde já treinou mais de 100 mil pessoas em todo o mundo.",
  //   title:
  //     "Keynote de abertura: WebXR? Realidade Virtual e Aumentada nativamente em navegadores",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "EW Academy",
  //   social_media: {
  //     instagram: "https://www.instagram.com/erickwendel_/",
  //     twitter: "http://twitter.com/erickwendel_",
  //     linkedIn: "https://www.linkedin.com/in/erickwendel",
  //     github: "https://github.com/ErickWendel",
  //     website: "https://www.youtube.com/channel/UCh84012dEUE076wM2CVFN9A",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 3,
  //   photo: "/speakers/2024/jordaniaBispo.png",
  //   name: "Jordânia Bispo",
  //   tech: "Carreira e desenvolvimento pessoal",
  //   topic:
  //     "A palestra traz os seguintes tópicos: Elementos básicos da Comunicação; Importância do feedback no ambiente de trabalho; Como evitar ruídos na comunicação entre líderes e liderados; Percepção Seletiva; Estilos de Comunicação (passiva, agressiva, passivo-agressiva e assertiva); Orientações para uma comunicação assertiva e estratégica.",
  //   mini_bio:
  //     "Jordânia Bispo é mestra em Comunicação pela Universidade Federal de Goiás (UFG) e graduada em Comunicação Social com Habilitação em Jornalismo pela Pontifícia Universidade Católica de Goiás (PUC Goiás). Possui experiência profissional em Comunicação Institucional, Comunicação Integrada e produção de conteúdo para web. Atualmente, é professora universitária, palestrante e mentora em Comunicação. Sua missão é ajudar profissionais autônomos, lideranças empresariais e times corporativos a se comunicarem de forma assertiva e estratégica.",
  //   title: "Comunicação assertiva para líderes",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "UNA | Comunicação Estratégica",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://br.linkedin.com/in/jord%C3%A2nia-bispo",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 4,
  //   photo: "/speakers/2024/fernandaWanderleyGDE.png",
  //   name: "Fernanda Wanderley",
  //   tech: "Inteligência artificial",
  //   topic:
  //     "Nessa palestra eu vou mostrar como desenvolvedores podem extrair o poder do Gemini pra acelerar suas tarefas fazendo, por exemplo, uma busca por código em um repositório do GitHub.",
  //   mini_bio:
  //     "Fernanda é formada em Ciência da Computação e Mestre em Inteligência Artificial pela UFRJ, Doutora em Inteligência Computacional pela UFMG e Google Developer Expert em Machine Learning. Contribui com projetos que incentivam grupos minorizados na tecnologia, sendo co-fundadora da MIA, embaixadora do WiDS Rio e colaboradora da PrograMaria.",
  //   title: "Explorando o Google Gemini: aplicações na engenharia de software",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 5,
  //   photo: "/speakers/2024/fernandoSedrezGDE.png",
  //   name: "Fernando Sedrez",
  //   tech: "Análise de dados",
  //   topic:
  //     "Nesta palestra, traremos um novo paradigma, incluir IA Generativa no pipeline de dados no BigQuery, com os modelos do Gemini é possível fazer o enriquecimento dos nossos dados, fazer novas descobertas e observações.",
  //   mini_bio:
  //     "Fernando Sedrez é especialista em engenheira de dados, Google Developer Expert em Google Cloud e Google Cloud Champion Innovator, com mais de 15 anos de carreira na área de tecnologia. Adora compartilhar conhecimento sobre a área de dados.",
  //   title: "Enriquecimento de dados no BigQuery com Gemini",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "Globo",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/fmsedrez/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 6,
  //   photo: "/speakers/2024/amandaLefevreGDE.png",
  //   name: "Amanda Lefévre",
  //   tech: "",
  //   topic: "",
  //   mini_bio: "Program Manager - GDG e GDE Latam",
  //   title: "Project Program Coordinator Google",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 7,
  //   photo: "/speakers/2024/arnaldoGualbertoGDE.png",
  //   name: "Arnaldo Gualberto",
  //   tech: "Machine Learning/TensorFlow",
  //   topic:
  //     "Você sabia que a Teoria dos Jogos está presente desde pequenas decisões cotidianas até questões globais de vida e morte? Nessa palestra, mergulharemos numa versão do problema mais famoso da Teoria dos Jogos: o Dilema do Prisioneiro. Exploraremos como estratégias aparentemente simples podem ser a chave para resolver conflitos, promover a cooperação e até mesmo evitar a destruição global. Além disso, veremos como as IAs mais modernas (como o Gemini) se comportam nesse jogo. Será que a IA tem algo pra ensinar a humanidade?",
  //   mini_bio:
  //     "Sua paixão por Redes Neurais fez Arnaldo se tornar Senior Machine Learning Engineer, Google Developer Expert, e Doutor em Deep Learning pela UFCG. Adora obras de arte, assistir filmes, e contar piadas ruins. Atualmente, está tentando aprender a jogar tênis, desenvolver o ouvido relativo e treinando sua mini Rede Neural Biológica.",
  //   title:
  //     "O que a Teoria dos Jogos e o Gemini tem a ver com a Vida, o Universo e Tudo Mais?",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "Advolve.ai",
  //   social_media: {
  //     instagram: "https://www.instagram.com/arnaldo.g12/",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/arnaldo-gualberto/",
  //     github: "https://github.com/arnaldog12",
  //     website: "https://medium.com/@arnaldog12",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 8,
  //   photo: "/speakers/2024/lucianoMartinsGDE.png",
  //   name: "Luciano Martins",
  //   tech: "Machine Learning/TensorFlow",
  //   topic: "Nesta palestra, exploraremos as ferramentas e tecnologias que vão impulsionar suas habilidades para enriquecer suas soluções com IA. Desde o uso da Gemini API, que facilita a integração de modelos em seus projetos, até frameworks avançados como Keras e JAX, que te darão o poder de construir soluções personalizadas. Vamos desvendar os segredos da família Gemma, com seus modelos abertos e flexíveis, e explorar as possibilidades da IA na borda com o Google AI Edge, levando a inteligência artificial para dispositivos móveis.  Junte-se a nós e descubra como o Google AI pode transformar a maneira como você cria aplicações e impulsionar sua carreira no mundo da tecnologia.",
  //   mini_bio:
  //     "Luciano é bacharel em ciências da computação, engenheiro de software há mais de 15 anos, é especialista em inteligência artificial e atua como Developer Advocate de Google AI. Luciano acredita que a tecnologia pode até mudar a vida das pessoas, mas só as pessoas podem mudar o mundo.",
  //   title: "Keynote de encerramento: As aventuras dos desenvolvedores com Google AI",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "Google",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/lucianommartins/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 9,
  //   photo: "/speakers/2024/marioSoutoGDE.png",
  //   name: "Mario Souto",
  //   tech: "Web",
  //   topic:
  //     "A ideia da talk, é passar uma intro de dado o enorme ruído que temos hoje na hora de estudar pra trabalhar com web, e mostrar como a pessoa pode ver de forma menor assuntos que no começo parecem complexos e passar um pouco da minha visão nesses mais de 6 anos dando aula, como estudar se baseando em problemas pode facilitar bastante a jornada. ",
  //   mini_bio:
  //     "Comecei a criar sites aos 11 anos, hoje com 25 e 10 anos de experiência em programação, sou Full Stack com foco em Front End. Dou aulas, já palestrei em eventos como BrazilJS e ajudei a resolver bugs no Google Chrome! Sou Staff Software Engineer no Nubank, Google Developer Expert, GitHub Star, Microsoft MVP e youtuber com mais de 4M de visualizações.",
  //   title: "Entrando no mundo dev, através da Web feat. AI",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "Nubank",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "http://linkedin.com/in/Omariosouto",
  //     github: "",
  //     website: "http://youtube.com/@DevSoutinho",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 10,
  //   photo: "/speakers/2024/egioArrudaGDE.png",
  //   name: "Egio Arruda",
  //   tech: "Workshop",
  //   topic:
  //     "O objetivo é demonstrar como desenvolver, em poucos passos, chatbots inteligentes utilizando Agent Builder, Vertex e DialogFlow",
  //   mini_bio:
  //     "Sou bacharel em Ciência da Computação pela UFG, além de pós-graduado pela FGV e também pelo Insper. Tenho 15 anos de experiência nas áreas de tecnologia e inovação e fui CTO e Co-Founder do EasyCrédito, o maior Hub de Crédito do Brasil. Atualmente sou Head of IT and Data no FitBank, uma das maiores Infratechs da América Latina. Além disso, atuo como Google Developer Expert em GCP e também sou professor convidado nas pós-graduações da PUC-Go e IPOG.",
  //   title: "Desenvolvendo Chatbots em minutos com Agent Builder",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/egiojr/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 11,
  //   photo: "/speakers/2024/mariaLuizeGDE.png",
  //   name: "Maria Luize",
  //   tech: "Google Earth Engine",
  //   topic:
  //     "Introdução às bases do sensoriamento remoto, com apresentação da plataforma Google Earth Engine, destacando seus usos e aplicações em conjunto com técnicas de Machine Learning e Deep Learning. Serão apresentados casos de sucesso, como a iniciativa MapBiomas, além da análise e avaliação dos resultados das segmentações geradas pelo MapBiomas para o bioma Cerrado. Essas análises são realizadas por meio do modelo LLM da Google Gemini. A apresentação, devido ao seu caráter abrangente, está estimada para durar aproximadamente 40 minutos. Entre as análises, o foco será nas principais transições de uso e cobertura da terra ao longo de 40 anos de dados, obtidos por meio de imagens da família de satélites Landsat, além das tendências de área observadas e perspectivas desenvolvidas pela LLM. A palestra use do modelo Gemini, porém não é focada nele.",
  //   mini_bio:
  //     "Maria Luize Pinheiro é engenheira da computação e pesquisadora especializada em Machine Learning e Deep Learning, com foco em visão computacional aplicada ao sensoriamento remoto. Participa da equipe de zona costeira no projeto MapBiomas, contribuindo para o mapeamento e monitoramento ambiental de classes presentes na zona costeira brasileira. Além de sua atuação técnica, é uma entusiasta da divulgação científica, buscando promover e ampliar o conhecimento dessa área no meio computacional.",
  //   title:
  //     "Cerrado Brasileiro: Revelações com Earth Engine, Deep Learning e Google Gemini",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/marialuize/",
  //     github: "https://github.com/MariaLuize",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 12,
  //   photo: "/speakers/2024/viniciusCaridaGDE.png",
  //   name: "Vinicius Caridá",
  //   tech: "Inteligência artificial",
  //   topic:
  //     "Nesta palestra, exploraremos o universo da inteligência artificial generativa (GenAI) com um foco técnico e prático. Começaremos abordando os conceitos fundamentais que sustentam a GenAI, desmistificando desde a base teórica até as aplicações avançadas. Através de uma análise detalhada dos modelos de IA da Google, incluindo o Gemini e a linha open source da família Gemma, você obterá uma compreensão clara de como esses modelos funcionam e como podem ser aplicados em diversos cenários. A palestra incluirá demonstrações práticas e hands-on, onde veremos como implementar e integrar essas tecnologias em projetos reais.",
  //   mini_bio:
  //     "Com mais de 15 anos de experiência em TI e inteligência artificial, sou Mestre e Doutor em Ciência da Computação, com especialização em IA. Atualmente, trabalho como Especialista Executivo em Dados e IA no Itaú Unibanco e atuo como professor na FIAP e ESPM, lecionando em programas de MBA focados em aprendizado de máquina, ciência de dados e inteligência empresarial. Minha expertise abrange vários campos, incluindo IA generativa, processamento de linguagem natural, assistentes virtuais, chatbots, mecanismos de recomendação, sistemas de controle e todo o ciclo de vida do MLOps. Sou reconhecido como um AWS Machine Learning Hero, um Google Developer Expert em aprendizado de máquina e um Google Champion Innovator. Além disso, atuei como consultor e mentor para startups do Google. Anteriormente, fui Microsoft MVP em IA de 2021 a 2022 e continuo liderando os grupos de usuários da AWS e Machine Learning/TensorFlow em São Paulo. Também sou co-chair dos workshops LatinX in AI (LXAI) em grandes conferências internacionais como AAAI, ICML e NeurIPS. Minhas contribuições técnicas são baseadas em um profundo comprometimento com o avanço da IA, ciência de dados e aprendizado de máquina, tanto academicamente quanto na indústria. Por meio do meu trabalho, pretendo aproveitar o poder da IA ​​e dos dados para impulsionar a inovação e criar resultados mais equitativos globalmente.",
  //   title: "Desvendando a GenAI: Da Teoria às Aplicações com Gemini e Gemma",
  //   gde: true,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn:
  //       "https://www.linkedin.com/in/viniciuscarida?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 13,
  //   photo: "/speakers/2024/ricardoRamos.png",
  //   name: "Ricardo Ribeiro",
  //   tech: "Carreira e desenvolvimento pessoal",
  //   topic:
  //     "Falaria sobre o dia a dia de um nômade digital, como conseguir passagens baratas, como viajar praticamente de graça, como fazer amizades ao redor do mundo viajando sozinho, buscar trabalho remoto, o que levo nas mochilas, etc... não é um tema técnico, porém é um tema de interesse de muitos desenvolvedores que sonham em rodar o mundo.",
  //   mini_bio:
  //     "Desenvolvedor FullStack, Baiano e Nômade Digital, com mais de 4 anos de experiência em desenvolvimento de software. Formado em Ciência da Computação e cursando MBA em Engenharia de Software. Atualmente trabalhando com Django e React, mas na maior parte da minha trajetória estive trabalhando com Node. Com experiência em projetos variados como sistemas de investigação/inteligência policial, CMS, gerenciamento de assinaturas, realidade aumentada, gerenciamento e monitoramento de plantas de produção, sistemas de RH, etc..., busco sempre desafios que estimulem minha criatividade. Fora do trabalho, sou nômade digital há quase dois anos, amante de viagens, jogos online e esportes.",
  //   title: "Anywhere Office: encontrando Wi-Fi e comunidades ao redor do mundo",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/rickrribeiro",
  //     github: "https://github.com/rickrribeiro/",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 14,
  //   photo: "/speakers/2024/bezaleelRamos.png",
  //   name: "Bezaleel Ramos",
  //   tech: "Infra/DevOps",
  //   topic:
  //     "A comunicação entre services pode ser complexa e cheia de desafios. Neste talk, vamos apresentar o Linkerd como uma solução poderosa para resolver esses problemas. Aprenderemos como o Linkerd pode lidar com balanceamento de carga, timeouts, retries em ambientes kubernetes. Além disso, discutiremos o funcionamento do Linkerd em configurações multi-cluster, destacando suas capacidades de integração e gestão em infraestruturas distribuídas.",
  //   mini_bio:
  //     "SRE na Jusbrasil e um dos organizadores do DevOpsDays Goiânia e DevOpsGO  sou responsável por garantir a alta disponibilidade e escalabilidade dos sistemas em ambientes kubernetes.",
  //   title: "Service Mesh com Linkerd em ambientes Multi-Cluster",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "Jusbrasil",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/bezarsnba/",
  //     github: "https://github.com/bezarsnba",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 15,
  //   photo: "/speakers/2024/caioCesar.png",
  //   name: "Caio César",
  //   tech: "Teste de Software",
  //   topic:
  //     "Revisão sobre tipo de testes e seus efeitos na qualidade do software.",
  //   mini_bio:
  //     "Mestre em Ciências da Computação com mais de 10 anos de experiencia na área de software. Especializado em arquitetura de software e atualmente diretor técnico na área de tecnologia.",
  //   title: "Fundamentos de Teste de Software",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/caiosousa2015/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 16,
  //   photo: "/speakers/2024/andersonCarlos.png",
  //   name: "Anderson Carlos",
  //   tech: "Machine Learning/TensorFlow",
  //   topic:
  //     "Irei explicar o que é fairness e vieses em modelos de IA de visão computacional, como metrificar e mitigar e comentar sobre o meu artigo aprovado na ECCV sobre o tema. Resumo em tópicos: impacto dos modelos enviesados na vida das pessoas; como a área de fairness lida com vieses em modelos; como metrificar os vieses; como mitigar eles; explicação do meu artigo; tudo será dentro do contexto da saúde (ex: vieses em modelos médicos); não é uma aula, é uma palestra para falar sobre o tema, a importância dele para toda pessoa que trabalhar com IA, conscientizar pessoas que não são da área sobre essa questão de fairness/IAs preconceituosas/vieses e passar por cima dessa demonstração rápida sobre metrificar e mitigar; o principal objetivo aqui é inspirar as pessoas sobre o tema",
  //   mini_bio:
  //     "Com background em engenharia mecatrônica, atuo com IA para visão computacional e NLP com instituições e empresas como Unifesp, HaiLab, Globo, e, através do Advanced Knowledge Center for Immersive Technologies (AKCIT). Com diversos papers com o tema de IA voltado para a saúde, um deles na ECCV, principal conferência de Visão Computacional da Europa.",
  //   title:
  //     "Vieses que Custam Vidas: O Papel da Fairness na Visão Computacional para a Saúde",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "Centro de Excelência em Inteligência Artificial (CEIA)",
  //   social_media: {
  //     instagram: "https://www.instagram.com/rson_data",
  //     twitter: "https://twitter.com/rson4data",
  //     linkedIn: "https://www.linkedin.com/in/andcarlos/",
  //     github: "https://github.com/E-crls/",
  //     website: "https://linktr.ee/rson_data",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 17,
  //   photo: "/speakers/2024/justiceFtc.png",
  //   name: "Carolina Linsmeyer",
  //   tech: "Robótica educacional",
  //   topic:
  //     "Na palestra iremos abordar o tema sobre como é a nossa preparação para a competição, o nosso cotidiano e como nós conseguimos obter ótimos resultados, tanto como formação profissional e pessoal de cada um. Pois apesar da competição ser difícil, em conjunto o trabalho pode se tornar divertido e efetivo.",
  //   mini_bio:
  //     "A Justice FTC é uma equipe de robótica da escola SESI Planalto de Goiânia, Goiás. Participamos do torneio nacional de robótica em Brasília, onde conseguimos alcançar resultados muito gratificantes. A competição, tem como propósito nos desafiar a projetar, construir e programar robôs por meio da tecnologia, para se movimentarem de uma maneira mais simples e autônoma. Além disso, também lidamos com várias áreas como o gerenciamento de projetos, marketing, eventos e a área financeira da equipe, com o objetivo de alcançar e impactar pessoas através de diferentes ações sociais, para levar nosso aprendizado e contribuição para todas as comunidades e famílias.",
  //   title: "Robótica Educacional voltada para competições de alto nível",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "https://www.instagram.com/justice.ftc/",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/justice-team-56046324b/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 18,
  //   photo: "/speakers/2024/camilaMoreira.png",
  //   name: "Camis Moreira",
  //   tech: "Gestão e metodologias ágeis",
  //   topic:
  //     "Vamos falar sobre como uma boa conversa pode transformar a dinâmica das equipes de tecnologia! Nesta palestra, vamos compartilhar dicas práticas para melhorar a colaboração, evitar mal-entendidos e garantir que todos estejam na mesma página. Venha descobrir como a comunicação clara e divertida pode ser o segredo para projetos inovadores e um ambiente de trabalho onde todos se sintam conectados e motivados.",
  //   mini_bio:
  //     "Camis é uma pessoa não binária, palestrante, mentora, educadora, founder de comunidade e especialista em E-commerce e Frontend. Atua como coordenadora de tecnologia em uma multinacional, possui certificação Google Project Management, e é MBA em Design Thinking e Gestão de Pessoas. Camis desempenha um papel crucial na liderança de times e no desenvolvimento de pessoas na área tech, participando ativamente em projetos de grande escala, tanto nacionais quanto internacionais.",
  //   title: "Comunicação em equipes de tecnologia: o pilar do sucesso",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "Accenture Brasil",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/camismoreira/",
  //     github: "",
  //     website: "",
  //     slide: "camismoreira-ecommerce.pdf",
  //   },
  // },
  // {
  //   id: 19,
  //   photo: "/speakers/2024/christiannePimenta.png",
  //   name: "Christianne Pimenta",
  //   tech: "Inteligência artificial",
  //   topic:
  //     "Nesta palestra, exploraremos os principais desafios éticos e de governança na implementação de sistemas de Inteligência Artificial (IA). Discutiremos como as regulamentações emergentes, como a ISO 42001, o Regulamento Europeu de IA e o Projeto de Lei 2338/2023 (PL 2030), estão moldando o cenário da IA, com foco em garantir transparência, segurança e responsabilidade nas aplicações tecnológicas. Abordaremos como essas normas e diretrizes podem ser aplicadas de forma prática para mitigar riscos, promover a inovação responsável e assegurar que as soluções de IA sejam desenvolvidas com base em princípios éticos sólidos. O objetivo é fornecer uma visão crítica sobre o papel da governança e das regulamentações na promoção de uma IA que beneficie toda a sociedade.",
  //   mini_bio:
  //     "Engenheira, atua ativamente em projetos de Inteligência Artificial, inovação e tecnologia, com mais de 15 anos de experiência organizacional e na liderança de projetos estratégicos. Mestranda em Planejamento e Desenvolvimento, é Black Belt mentora de startups pela 100Open e possui diversas especializações e certificações. Atua como head de operações na Simeon e é professora de IA e tecnologia, além de atuar ativamente em comitês de governança e no ecossistema de inovação.",
  //   title: "Ética e IA: Governança e Regulamentações",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/christiannepimenta",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 20,
  //   photo: "/speakers/2024/fayraTolentino.png",
  //   name: "Fayra Tolentino",
  //   tech: "Workshop",
  //   topic:
  //     "Este workshop, tem como objetivo fornecer uma compreensão prática e acessível sobre como utilizar as APIs do Open Gateway da Telefónica para desenvolver e implementar aplicativos na nuvem usando o Google Cloud. Ao final do workshop, a pessoa participante terá as habilidades  básicas necessárias para criar e gerenciar aplicativos na nuvem, aproveitando ao máximo as funcionalidades do Google Cloud e as APIs do Open Gateway. Tópicos-Chave: Introdução às APIs: Conceito de API e seu papel na comunicação entre diferentes sistemas. Exemplos práticos de como as APIs são usadas no desenvolvimento de aplicativos. APIs do Open Gateway da Telefónica: O que são as APIs do Open Gateway e como elas funcionam. Benefícios e casos de uso das APIs do Open Gateway para desenvolvedores. Open Gateway : GSMA , CAMARA e Telefónica. Google Cloud: Introdução ao Google Cloud e suas principais funcionalidades. Passos para configurar um ambiente de desenvolvimento no Google Cloud. Como integrar e gerenciar APIs do Open Gateway no Google Cloud.",
  //   mini_bio:
  //     "Fayra Miranda é arquiteta urbanista de formação que encontrou na tecnologia e na educação uma poderosa ferramenta para transformar realidades. Com uma carreira diversificada como criadora de conteúdo, desenvolvedora, mentora e DevRel, Fayra se empenha em compartilhar conhecimento de alta qualidade e promover a inclusão no universo tecnológico. Sua dedicação em empoderar mulheres na tecnologia se manifesta através de seu trabalho voluntário em projetos sociais, onde se esforça para aumentar a presença feminina no setor.",
  //   title:
  //     "Decolando na Nuvem: Crie e Inove com APIs do Open Gateway no Google Cloud",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/fayramiranda/",
  //     github: "https://github.com/MirandaFayra",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 21,
  //   photo: "/speakers/2024/franciellyMoraes.png",
  //   name: "Francielly de Moraes",
  //   tech: "Mobile",
  //   topic:
  //     "Modularização vem sendo usada como a solução de problemas que envolvem separação escopos e até mesmo soluções micro-frontend para grandes projetos. Mas e quando ela começa a se tornar um problema? Essa palestra vai trazer exemplos reais de problemas decorrentes de um modularização mal planejada e como solucioná-los",
  //   mini_bio: "",
  //   title: "Android e Modularização: Quando modularizar vira um problema",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/franms/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 22,
  //   photo: "/speakers/2024/geovanaPereira.png",
  //   name: "Geovana Pereira",
  //   tech: "Gestão da informação",
  //   topic:
  //     "A palestra Gestão da Informação, Inovação e Tecnologia: O Futuro da Competitividade explora a interconexão crítica entre esses três elementos essenciais para o sucesso organizacional no cenário atual. Iniciando com a gestão da informação, a palestra destaca como a coleta, armazenamento, processamento e análise eficaz de dados são fundamentais para a tomada de decisões informadas e para a otimização dos processos empresariais. Avançando para o tema da inovação, o foco se volta para o papel transformador da criatividade e do desenvolvimento contínuo nas organizações. A palestra delineia os diferentes tipos de inovação e oferece estratégias para cultivar uma cultura inovadora que impulsione o crescimento e a adaptação às mudanças do mercado. Exemplos de empresas bem-sucedidas que têm utilizado a inovação como um diferencial competitivo serão compartilhados para ilustrar esses conceitos. E, por fim, abordarei a tecnologia, como facilitadora e catalisadora da mudança. A palestra examina como tecnologias emergentes, como Inteligência Artificial, Big Data e Internet das Coisas (IoT), estão moldando novos modelos de negócios e transformando operações. Finalmente, a palestra integra os três elementos—gestão da informação, inovação e tecnologia—mostrando como a sinergia entre eles pode criar uma base sólida para a competitividade e o sucesso organizacional. A conclusão incluirá um resumo dos principais pontos discutidos e uma sessão de perguntas e respostas para aprofundar a compreensão e esclarecer dúvidas dos participantes.",
  //   mini_bio:
  //     "Olá! Sou Geovana Correia, Analista de Serviços de Tecnologia e Inovação no SENAI Goiás, com foco de atuação no SENAI Hub Goiás. Minha paixão por novos conhecimentos e desafios me guia todos os dias, e no SENAI Hub, meu objetivo é conectar-me com pessoas e ambientes inovadores. Com uma formação em Gestão da Informação pela UFG e atualmente cursando um mestrado em Comunicação na mesma instituição, estou sempre em busca de novos aprendizados e compartilho minha experiência organizando Ideathons com minha equipe no SESI/SENAI e participando de torneios de robótica. Se você quiser saber mais sobre meus projetos ou conversar, fique à vontade para visitar meu Instagram @geovanapcorreia.",
  //   title:
  //     "Gestão da Informação, Inovação e Tecnologia: O Futuro da Competitividade",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "https://www.instagram.com/geovanapcorreia/",
  //     twitter: "",
  //     linkedIn: "",
  //     github: "",
  //     website: "https://bio.site/eusougeovanacorreia",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 23,
  //   photo: "/speakers/2024/joaoVictor.png",
  //   name: "João Victor",
  //   tech: "Workshop",
  //   topic:
  //     "Pretendo entregar um portfolio de site pessoal com vários projetos a todos os integrantes do workshop e entregar desde o ensinar a base das tecnologias usadas, conteúdo, lógica, código, versionamento, até o deploy online!",
  //   mini_bio:
  //     "Estudante de graduação sistemas de informação. Desenvolvedor fullstack-web. Pesquisador Científico e extensionista na Universidade Estadual do Tocantins. Professor de criação de sites na Fundação de Apoio a Ciência e Tecnologia do Tocantins",
  //   title:
  //     "Projeto de site pessoal em menos de 1 hora! Como se destacar tendo um portfólio pessoal",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn:
  //       "https://www.linkedin.com/in/jo%C3%A3o-victor-p%C3%B3voa-fran%C3%A7a-97502420b/",
  //     github: "https://github.com/JoaoIto",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 24,
  //   photo: "/speakers/2024/kadidjaValeria.png",
  //   name: "Kadidja Valéria",
  //   tech: "Carreira e desenvolvimento pessoal",
  //   topic:
  //     "A subrepresentação das mulheres na indústria de games. Estereótipos de gênero e seus impactos. Histórias inspiradoras de mulheres que fizeram a diferença",
  //   mini_bio:
  //     "Kadidja Valéria é participante das comunidades PyLadiesDF, LadiesTechdo UDF e Meninas nas Ciência do IFB. É Analista de Sistemas, arquivista e tecnóloga em Gestão Pública, Mestra e Doutoranda em Ciência da Informação pela UnB. É Professora nos cursos de Tecnologias na UDF. É também Especialista em E-learning e desenvolve projetos com metodologias ativas e analítica na educação à distância. Educação continuada e capacitação constante é o seu lema.",
  //   title: "Quebrando Barreiras: Mulheres na Indústria de Games",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://br.linkedin.com/in/kadidja-oliveira-60431768",
  //     github: "https://github.com/Kadidjah",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 25,
  //   photo: "/speakers/2024/lucivaniaBorges.png",
  //   name: "Lucivania Borges",
  //   tech: "Inteligência artificial",
  //   topic:
  //     "O impacto psicológico que a IA tem causado na vida do humano, interação homem-computador, etc.",
  //   mini_bio:
  //     "Sou uma educadora com vasta experiência, mestre em Psicologia Educacional e especialista em inteligência artificial. Com mais de três décadas em sala de aula, ministra aulas sobre oratória e didática, além de realizar pesquisas sobre a aplicação da inteligência artificial na educação. Atualmente, atua como professora universitária e gerente administrativa financeira, combinando sua paixão por ensinar com sua expertise em gestão.",
  //   title: "IA e o comportamento do ser humano",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/luciv%C3%A2nia-borges-6bb44234/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 26,
  //   photo: "/speakers/2024/marceloPaiva.png",
  //   name: "Marcelo Paiva",
  //   tech: "Carreira e desenvolvimento pessoal",
  //   topic:
  //     "Nesta palestra, exploraremos a evolução do desenvolvimento de software com a presença da IA, desde as metodologias tradicionais até as soluções atuais. Destacaremos ferramentas de grandes players como Google Cloud AI, Amazon CodeCatalyst e Microsoft  AI, mostrando seu impacto no presente e o que elas prometem para o futuro. Vamos discutir como a IA está moldando o futuro da programação e o que os desenvolvedores podem esperar dessa revolução.",
  //   mini_bio: "CTO na Softprime | Microsoft MVP | AWS Community Builder",
  //   title:
  //     "Passado, Presente e Futuro do Desenvolvimento de Software: A Revolução com IA",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/marcelopaiva/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 27,
  //   photo: "/speakers/2024/marianaLemes.png",
  //   name: "Mariana Lemes",
  //   tech: "UX/UI",
  //   topic:
  //     "Quero falar sobre Como a IA está revolucionando o design de UX e criando novas oportunidades na área de design. Também quero abordar um tema mais prático, onde faço uma atividade para todos sairem da caixa e começarem a ver as novas tecnologias, novos processos como oportunidade.",
  //   mini_bio:
  //     "Eu sou uma mulher negra e lésbica que sempre estudou muito e sempre pesquisou muito para poder entregar o melhor trabalho, eu comecei trabalhando como estagiária no TRE, depois fui trabalhar de Call Center na Vivo, depois entrei de telefonista na TOTVS, lá dentro tive oportunidade de fazer uma faculdade de Analise e Desenvolvimento de sistemas, depois fiz MBA em Banco de dados e comecei a me apaixonar pode Design Thinking observando e assistindo palestras de UX design, então comecei a estudar um pouco mais sobre e decidi fazer MBA em UX design. Em Abril do ano de 2023 fui contratada com Product desig pela Start-up Positiva Soluções, onde crio conteúdos de marketing para os produtos, desenho protótipos, desenho jornadas, faço vídeos instrucionais, vídeos para mídias sociais além de coordenar todas as pesquisas de novos produtos.",
  //   title: "UX e Inteligência Artificial: Transformando Experiências Digitais",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "linkedin.com/marianalemes90",
  //     github: "",
  //     website:
  //       "https://medium.com/@marycriativeapp/portf%C3%B3lio-desenvolvedor-front-end-d56823baddb4",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 28,
  //   photo: "/speakers/2024/natalieTolentino.png",
  //   name: "Natalie Tolentino",
  //   tech: "Web",
  //   topic:
  //     "A importância de uma comunicação eficiente e ética, tanto entre humanos quanto entre máquinas, incluindo os desafios na era digital. As Três Peneiras de Sócrates: A relação entre verdade, bondade e utilidade na comunicação, e como aplicá-las. Protocolos de Comunicação na Internet: Definição, exemplos (HTTPS, I2C, Websocket), e a importância dos protocolos para garantir a integridade e eficiência da comunicação. Relação entre Protocolos e as Três Peneiras: Como os protocolos garantem autenticidade, segurança e eficiência. Ética Digital e Leis de Trânsito: Paralelos entre o comportamento digital e as regras de trânsito, incentivando uma navegação segura e responsável. Exemplos de Ética Digital e Segurança: Respeito, privacidade, verificação de informações no ambiente virtual.",
  //   mini_bio:
  //     "Desenvolvedora de software, investigadora da Natureza e amante dos astros. Atua com programação web há 5 anos, coordena o Nucleo de Pesquisas Aeroespaciais da UFG e estuda Filosofia. Mãe, filósofa e uma eterna curiosa sobre a vida, universo e tudo mais.",
  //   title:
  //     "Comunicação: de protocolos à boas práticas - Como humanos e máquinas se comunicam",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/natalie-tolentino",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 29,
  //   photo: "/speakers/2024/olivarTamele.png",
  //   name: "Olivar Tamele",
  //   tech: "Mobile",
  //   topic:
  //     "Descubra como o Flutter revolucionou o desenvolvimento de aplicativos móveis. Nesta palestra, vamos explorar os motivos pelos quais você deve escolher o Flutter para criar apps de alta performance para iOS e Android a partir de uma única base de código. Aprenderemos sobre os principais benefícios do Flutter, como a interface rica e personalizável, o desenvolvimento rápido e a comunidade ativa.",
  //   mini_bio:
  //     "Me chamo Olivar Tamele, tenho 22 anos atuo com Desenvolvedor Flutter e sou Founder e CEO da empresa TWT Software, líder da comunidade Black Stars e embaixador da Rocketseat. Durante minha carreira, tive a honra de receber o Prêmio IEL de Estágio em etapas estadual e nacional, na categoria Projetos Inovadores e conquistei o Segundo Lugar na First Lego League, na categoria Projeto de Inovação, graças ao desenvolvimento do aplicativo Super Kids. Embora ja atue com as ferramentas, Dart, Flutter, Firebase e Google Cloud estou focado em estudar essas tecnologias afim de chegar ao maior nível de expertise possível.",
  //   title: "Por que utilizar Flutter como base para aplicaçoes mobiles",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://linktr.ee/olivar.dev",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 30,
  //   photo: "/speakers/2024/pedroFrancisco.png",
  //   name: "Pedro Francisco",
  //   tech: "Mobile",
  //   topic:
  //     "O que é SOLID? Como isto pode ajudar a melhorar a qualidade em qualquer projeto de software? Quais ferramentas podem nos auxiliar para resolver a tão temida DI (o vulgo D do soliD)? Em suma, abordaremos princípios, aplicabilidade e ferramental. Sendo os 2 últimos demonstrados no framework Android e Koin.",
  //   mini_bio:
  //     "Atua há mais de 12 anos como desenvolvedor de software de aplicações móveis, sempre focado em android. Já trabalhou como desenvolvedor, freelancer, já abriu e faliu uma empresa e nos últimos 4 anos atua como consultor em projetos nacionais e internacionais no segmento de fintechs.",
  //   title: "Princípios do SOLID aplicados em projetos Android",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/pedrofsn/",
  //     github: "https://github.com/pedrofsn/",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 31,
  //   photo: "/speakers/2024/pedroLima.png",
  //   name: "Pedro Lima",
  //   tech: "Web",
  //   topic:
  //     "Vamos explorar de forma leve e divertida como o front-end e o WordPress podem ser ferramentas poderosas para o desenvolvimento pessoal. Pedro vai compartilhar como ele transforma códigos em sites dinâmicos e intuitivos que ajudam empresas e pessoas a se conectarem com seu público de maneira mais profunda. Seja você um novato em design ou um veterano em tecnologia, essa palestra vai mostrar como pequenas mudanças no código podem gerar grandes impactos na vida das pessoas.",
  //   mini_bio:
  //     "Sou Pedro Lima, tenho 22 anos e sou apaixonado por tecnologia e desenvolvimento humano. Atualmente, sou CTO de uma das maiores empresas de treinamento humano no Brasil, onde aplico inovação e visão estratégica. Tive a honra de trabalhar com Erico Rocha, fundador do '6 em 7' e da Fórmula de Lançamento, além de ter atuado como desenvolvedor front-end em projetos de destaque na NV99 (Flow Podcast) e GitHub Brasil",
  //   title: "Código de Impacto: Front-end e WordPress em Ação",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // // {
  // //   id: 32,
  // //   photo: "/speakers/2024/sandroMoreira.png",
  // //   name: "Sandro Moreira",
  // //   tech: "Machine Learning/TensorFlow",
  // //   topic:
  // //     "Vamos desmistificar o grande entusiasmo em torno da inteligência artificial generativa (IAG). Exploraremos os conceitos básicos por trás dessa tecnologia revolucionária, que tem a capacidade de criar novos conteúdos, como textos e imagens. Além disso, discutiremos as diversas aplicações da IAG em diferentes setores e os desafios que a acompanham, como questões éticas e viés algorítmico. O objetivo é apresentar um panorama completo sobre a IAG, separando o que é real do que é exagero, e fornecer insights valiosos para profissionais e entusiastas da área.",
  // //   mini_bio:
  // //     "Especialista em IA, Mentor do Google for Startups, Palestrante, Professor na UNIRV e Pesquisador de IA no Centro de Excelência em IA (CEIA-UFG)",
  // //   title: "IA Generativa: O HYPE e a REALIDADE por trás da Tecnologia",
  // //   gde: false,
  // //   showOnSite: true,
  // //   companyTitle: "",
  // //   social_media: {
  // //     instagram: "",
  // //     twitter: "",
  // //     linkedIn: "https://www.linkedin.com/in/sandro-moreira",
  // //     github: "",
  // //     website: "",
  // //     slide: "",
  // //   },
  // // },
  // {
  //   id: 33,
  //   photo: "/speakers/2024/taisSilva.png",
  //   name: "Tais Silva",
  //   tech: "Machine Learning/TensorFlow",
  //   topic:
  //     "Você saberia identificar um conteúdo gerado por Inteligência Artificial? Na era da inteligência artificial, garantir que os modelos de linguagem gerem conteúdo confiável e livre de vieses é crucial. Nesta palestra, exploraremos a técnica de marca d'água como uma ferramenta promissora para garantir a honestidade e a rastreabilidade dos modelos de linguagem.",
  //   mini_bio:
  //     "Tecnóloga em sistemas para internet pela Fatec Santos, mestranda em ciência da computação no IME-USP e analista de dados na SAS Institute. Também embaixadora do Women Techmakers, fundadora do GDG Santos, co-organizadora no WiMLDS São Paulo, bailarina, florista, leitora assídua, fotógrafa e voluntária das causas animais.",
  //   title:
  //     "Keynote: Mantendo a IA Honesta: Marca D'Água para Modelos de Linguagem",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://linkedin.com.br/in/tcrsilva",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 34,
  //   photo: "/speakers/2024/tiagoGoncalves.png",
  //   name: "Tiago Gonçalves",
  //   tech: "Inteligência artificial",
  //   topic:
  //     "Nesta palestra, exploraremos como integrar Grandes Modelos de Linguagem (LLMs), como GPT e Ollama, em aplicações Java para criar soluções inteligentes e eficientes. Discutiremos as principais bibliotecas que facilitam essa integração (Spring AI e LangChain4j), além de mostrar exemplos práticos de processamento de linguagem natural (NLP) com Java. Tópicos da palestra: Introdução aos LLMs e Aplicações em Java (10 min); Visão Geral do Spring AI (15 min); Introdução ao LangChain4j (10 min); Integração de LLMs com Spring AI e LangChain4j (10 min); Perspectivas Futuras e Tendências com LLMs, Spring AI e LangChain4j (3 min); Sessão de Perguntas e Respostas (2 min).",
  //   mini_bio:
  //     "Eu acredito que a tecnologia tem o poder de simplificar o mundo e que compartilhar conhecimento acelera esse processo. Atualmente, no desenvolvimento backend com Java, dedico-me a simplificar a vida de diversos usuários em áreas como financeiro e logístico, entregando valor por meio de soluções eficazes. Não foco apenas em simplificar processos, mas também de compartilhar descobertas e aprendizados com a comunidade, contribuindo para o avanço coletivo no campo da tecnologia.",
  //   title: "Java e LLMs: Explorando a inovação no desenvolvimento de software",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/vieira-tg/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 35,
  //   photo: "/speakers/2024/vanessa.png",
  //   name: "Vanessa Sousa",
  //   tech: "UX/UI",
  //   topic:
  //     "As gerações e a tecnologia tem evoluído juntas, e numa velocidade que muitas vezes é difícil acompanhar. E isso tem impactado na criação de estratégias, vendas, desenvolvimento de novos produtos e a manutenção dos que já existem. Por causa dessa rapidez a exigência por melhores experiências aumenta ou diminui dependendo do comportamento das pessoas e dos produtos. O impacto de tudo isso recai sobre como fazemos bons designs e projetamos novas ideias. Nessa palestra vamos ver exemplos de como mudar rapidamente e adaptar o design as diferentes gerações que o consomem, inserindo principalmente o conceito de ux writing e seus processos. Como os entregaveis e o ferramental podem amparar os profissionais da área. E como observar o comportamento da pessoa usuária pra aplicar melhorias em nossos produtos. ",
  //   mini_bio:
  //     "UX Writer, Designer, Desenvolvedora e Curadora de IAs Conversacionais, Tutora, Palestrante e Voluntária. Formada em Análise e Desenvolvimento de Sistemas e fruto de transição de carreira. Apaixonada por comunidades, acredita no poder de transformação de quando estamos em união pelo mesmo objetivo.Casada, mãe de pet, aquariana, geek, techmaromba, ama shows, comida e Coca Cola.",
  //   title: "O Futuro do Design: Um mundo multigeracional",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "www.linkedin.com/in/vanessa20sousa",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 36,
  //   photo: "/speakers/2024/victoriaGabrielle.png",
  //   name: "Victoria Gabrielle",
  //   tech: "Análise de dados",
  //   topic:
  //     "Pretendo abordar maior parte do processo de criação de personagens, Historia e Referencias culturais no design de jogos como Horizon Forbidden West, Ori and the Blind Forest e até mesmo o Fortnite. Também Mencionando a evolução do uso de motores gráficos e sua complexidade",
  //   mini_bio:
  //     "Desenvolvedora apaixonada por jogos, focada em criação de personagens e narrativa. Adoro explorar o processo cultural dos games, do design de roupas às ferramentas. 🎮✨",
  //   title: "Criação de Personagem e Evolução das Engines",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/torigabrielle/",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 37,
  //   photo: "/speakers/2024/alyceSuzaNew.png",
  //   name: "Alyce Suza",
  //   tech: "Cibersegurança",
  //   topic:
  //     "Nesta palestra iremos discutir estratégias praticas e dicas simples para evitar problemas de segurança no ambiente digital. Os tópicos abordados serão a importância de aprender segurança, os ataques mais conhecidos e como previni-los.",
  //   mini_bio:
  //     "Sou Analista de Cibersegurança com foco em gestão e análise de vulnerabilidades. Minha experiência inclui a identificação e mitigação de riscos, testes de penetração e implementação de políticas de segurança robustas. Além disso, tenho uma forte linha de estudo voltada para pesquisa, palestras e conscientização em cibersegurança, buscando sempre compartilhar conhecimento e promover práticas seguras no ambiente digital.",
  //   title:
  //     "Fique longe de problemas: Praticas de prevenção de risco cibernético",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/alyce-suza",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 38,
  //   photo: "/speakers/2024/igorMuniz.png",
  //   name: "Igor Muniz",
  //   tech: "Machine Learning/TensorFlow",
  //   topic:
  //     "O Hermes utiliza Inteligência Artificial e APIs de georreferenciamento para aprimorar o atendimento a chamados de emergência. Através da captura do áudio da ligação para os números de emergência (190, 193 etc.), as informações importantes sobre a emergência são cadastradas e enviadas às equipes que realizarão o atendimento. Integrado ao SINESPCAD, sistema de atendimento e despacho de ocorrências do Ministério da Justiça, busca tornar o processo mais ágil e eficiente.",
  //   mini_bio:
  //     "Tenente-Coronel do Corpo de Bombeiros Militar do Distrito Federal (CBMDF), atualmente está cedido ao Ministério da Justiça como Coordenador de Implantação do Sistema Nacional de Informações de Segurança Pública (SINESP). Mestrando em Gestão da Inovação pela Universidade de Brasília (UnB) e Pós-graduando em Inteligência Artificial e Aprendizagem de Máquina pela PUC-Minas. Entusiasta em automatizar tarefas repetitivas, vê na IA a oportunidade de ouro para delegarmos o trabalho maçante à máquina e deixarmos o trabalho humano cada vez mais humano.",
  //   title: "Hermes: Atendendo Chamados de Emergências com IA",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/munizigor",
  //     github: "https://www.github.com/munizigor",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 39,
  //   photo: "/speakers/2024/gustavoRibeiro.png",
  //   name: "Gustavo Ribeiro",
  //   tech: "Inteligência artificial",
  //   topic:
  //     "Todos nós utilizamos IA no dia-a-dia. Mas você já parou para pensar na responsabilidade e ética que as IAs que usamos devem ter? O Google possui 7 princípios que guiam o uso e desenvolvimento desses sistemas, e iremos abordar esses tópicos e entender como são utilizados na prática.",
  //   mini_bio:
  //     "Engenheiro Cloud com anos de experiência em diversos setores, certificado por empresas líderes em tecnologia como Amazon, Microsoft, Google e Astronomer. Palestrante em eventos de tecnologia no Brasil e no exterior. Lidera uma comunidade do Google no Brasil, o GDG Cloud Brasília. Possui vasta experiência em projetos inovadores de plataforma de dados e ambientes multicloud em toda a América Latina. Atualmente focado em Cloud FinOps e atuando como especialista em tecnologia e inovação para órgãos federais brasileiros, dedicado a promover soluções eficazes para problemas e fomentar uma cultura de transformação contínua.",
  //   title: "Keynote: Responsible AI no Google",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/gustavribeiro/",
  //     github: "",
  //     website: "https://taggo.one/gustavosantossr",
  //     slide: "",
  //   },
  // },
  // // {
  // //   id: 40,
  // //   photo: "/speakers/2024/camillaMartins.png",
  // //   name: "Camilla Martins",
  // //   tech: "Infra/Devops",
  // //   topic: "",
  // //   mini_bio:
  // //     "Não-binário. Punk, paulista, santista. Docker Community Leader. Sou Senior Site Reliability Engineer e atualmente trabalho na Storyblok, com pós em Forense Computacional e Mestre em Operação, Avaliação e Gerenciamento Avançado de Redes de Computadores na Universidade Federal do Estado do Rio de Janeiro. Iniciando agora meu Doutorado também pela Federal do Estado do Rio de Janeiro. Sou Docker Community Leader premiada duas vezes pela Docker Inc, Docker Captain, DevOpsDays Core Organizer, Impulso Expert, VeeCode Ambassador, Google Developer Expert em Cloud, Hashicorp Ambassador, organizadora e palestrante de DevOpsDays pelo Brasil e instrutora e curadora de conteúdo pela LinuxTips. Nas horas vagas, estou curtindo a vida viajando por aí (já viajei 16 países e contando) e afofando meus gatinhos pretos <3 ela/ele https://pronoun.is/they",
  // //   title: "",
  // //   gde: false,
  // //   showOnSite: true,
  // //   companyTitle: "",
  // //   social_media: {
  // //     instagram: "",
  // //     twitter: "",
  // //     linkedIn: "",
  // //     github: "",
  // //     website: "",
  // //     slide: "",
  // //   },
  // // },
  // {
  //   id: 41,
  //   photo: "/speakers/2024/weslleySantos.png",
  //   name: "Weslley Santos",
  //   tech: "Carreira e desenvolvimento pessoal",
  //   topic:
  //     "Com foco em sobre como existir e se destacar em um mercado de títulos intimidadores, conto sobre como o open-source me ajudou a superar a síndrome do impostor até conquistas inimagináveis que refletem diretamente na vida profissional.",
  //   mini_bio:
  //     "Desenvolvedor ativo no ecossistema open-source. Co-mantenedor do MySQL2 e criador do test runner Poku. Impacta milhões de projetos e desenvolvedores globalmente através do open-source",
  //   title:
  //     "Superando a síndrome do impostor e os desafios de existir no mercado através do open-source",
  //   gde: false,
  //   showOnSite: true,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "https://www.linkedin.com/in/wellwelwel",
  //     github: "https://github.com/wellwelwel",
  //     website: "",
  //     slide: "",
  //   },
  // },
  // {
  //   id: 42,
  //   photo: "/favicon.ico",
  //   name: "Luciano Martins e Fernanda Wanderley",
  //   tech: "Workshop",
  //   topic: "Participe desta imersão usando o colab e o Gemini API para aprender e exercitar como utilizar a IA do Google para otimizar e acelerar seu processo de desenvolvimento de soluções.",
  //   mini_bio: "",
  //   title: "Prototipando ideias com Google AI",
  //   gde: false,
  //   showOnSite: false,
  //   companyTitle: "",
  //   social_media: {
  //     instagram: "",
  //     twitter: "",
  //     linkedIn: "",
  //     github: "",
  //     website: "",
  //     slide: "",
  //   },
  // },
  {
    id: 1,
    photo: "/speakers/aDefinir.png",
    name: "A definir",
    tech: "A definir",
    topic: "",
    mini_bio: "",
    title: "",
    gde: false,
    showOnSite: true,
    companyTitle: "",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "",
      github: "",
      website: "",
      slide: "",
    },
  },
  {
    id: 2,
    photo: "/speakers/aDefinir.png",
    name: "A definir",
    tech: "A definir",
    topic: "",
    mini_bio: "",
    title: "",
    gde: false,
    showOnSite: true,
    companyTitle: "",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "",
      github: "",
      website: "",
      slide: "",
    },
  },
  {
    id: 3,
    photo: "/speakers/aDefinir.png",
    name: "A definir",
    tech: "A definir",
    topic: "",
    mini_bio: "",
    title: "",
    gde: false,
    showOnSite: true,
    companyTitle: "",
    social_media: {
      instagram: "",
      twitter: "",
      linkedIn: "",
      github: "",
      website: "",
      slide: "",
    },
  },
];

export default speakers;
